version: '3.8'
networks:
  compose_network:

services:

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - frontend:/app:cached
    environment:
      - NODE_ENV=development
    command: npm run dev
    networks:
      compose_network:

  proxy:
    build:
      context: proxy
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - proxy:/app:cached
    command: cargo run --package proxy --bin proxy
    networks:
      compose_network:
    depends_on:
      - frontend

volumes:
  frontend:
  proxy: